#############################################################################
# Generated by PAGE version 5.0.2
#  in conjunction with Tcl version 8.6
#  Sep 17, 2020 03:45:32 PM EDT  platform: Linux
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set desc "-family {DejaVu Sans} -size 0"
set vTcl(actual_gui_font_text_desc) $desc
set vTcl(actual_gui_font_text_name) [font create {*}$desc]
set desc "-family {DejaVu Sans Mono} -size 12"
set vTcl(actual_gui_font_fixed_desc) $desc
set vTcl(actual_gui_font_fixed_name) [font create {*}$desc]
set desc "-family {DejaVu Sans} -size 0"
set vTcl(actual_gui_font_menu_desc) $desc
set vTcl(actual_gui_font_menu_name) [font create {*}$desc]
set desc "-family {DejaVu Sans} -size 12"
set vTcl(actual_gui_font_tooltip_desc) $desc
set vTcl(actual_gui_font_tooltip_name) [font create {*}$desc]
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m72" -background $vTcl(actual_gui_bg) \
        -highlightbackground #464646 -highlightcolor black
    wm focusmodel $top passive
    wm geometry $top 792x935+2624+137
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 5745 1050
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "Data Director Revolution"
    vTcl:DefineAlias "$top" "ddrWindow" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    label $top.lab47 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans} -size 12 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Alert:
    vTcl:DefineAlias "$top.lab47" "lbl_alert" vTcl:WidgetProc "ddrWindow" 1
    label $top.lab70 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans} -size 12 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Health:
    vTcl:DefineAlias "$top.lab70" "lbl_health" vTcl:WidgetProc "ddrWindow" 1
    set site_3_0 $top.m72
    menu $site_3_0 \
        -activebackground #464646 -activeforeground #464646 \
        -background #464646 -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0
    ttk::style configure TNotebook -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -foreground $vTcl(actual_gui_fg)
    ttk::style configure TNotebook.Tab -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style map TNotebook.Tab -background [list disabled $vTcl(actual_gui_bg) selected $vTcl(pr,guicomplement_color)]
    ttk::notebook $top.tNo47 \
        -width 792 -height 503
    vTcl:DefineAlias "$top.tNo47" "t_notebook" vTcl:WidgetProc "ddrWindow" 1
    frame $top.tNo47.t0 \
        -background $vTcl(actual_gui_bg) -highlightcolor black
    vTcl:DefineAlias "$top.tNo47.t0" "t_notebook_t0" vTcl:WidgetProc "ddrWindow" 1
    $top.tNo47 add $top.tNo47.t0 \
        -padding 0 -sticky nsew -state normal -text Record -image {} \
        -compound left -underline -1
    set site_4_0  $top.tNo47.t0
    labelframe $site_4_0.lab56 \
        -font {-family {DejaVu Sans} -size 12 -weight bold} -foreground black \
        -text {Data Director Revolution} -background $vTcl(actual_gui_bg) \
        -height 455 -highlightcolor black -width 770
    vTcl:DefineAlias "$site_4_0.lab56" "label_frame2" vTcl:WidgetProc "ddrWindow" 1
    set site_5_0 $site_4_0.lab56
    button $site_5_0.but68 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -command shadow \
        -font {-family {DejaVu Sans} -size 36} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Shadow
    vTcl:DefineAlias "$site_5_0.but68" "btn_shadow" vTcl:WidgetProc "ddrWindow" 1
    button $site_5_0.but69 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -command manual \
        -font {-family {DejaVu Sans} -size 36} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Manual
    vTcl:DefineAlias "$site_5_0.but69" "btn_manual" vTcl:WidgetProc "ddrWindow" 1
    entry $site_5_0.ent75 \
        -background white -font $vTcl(actual_gui_font_fixed_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -insertbackground black -justify right -selectbackground #c4c4c4 \
        -selectforeground black
    vTcl:DefineAlias "$site_5_0.ent75" "ent_rec_name" vTcl:WidgetProc "ddrWindow" 1
    label $site_5_0.lab76 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans} -size 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Manual Recording Name:}
    vTcl:DefineAlias "$site_5_0.lab76" "lbl_rec_name" vTcl:WidgetProc "ddrWindow" 1
    label $site_5_0.lab44 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans} -size 12} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Active KML:}
    vTcl:DefineAlias "$site_5_0.lab44" "lbl_active_kml" vTcl:WidgetProc "ddrWindow" 1
    entry $site_5_0.ent45 \
        -background white -font $vTcl(actual_gui_font_fixed_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -insertbackground black -justify right -selectbackground #c4c4c4 \
        -selectforeground black -state readonly -width 476
    vTcl:DefineAlias "$site_5_0.ent45" "txtbox_active_kml" vTcl:WidgetProc "ddrWindow" 1
    place $site_5_0.but68 \
        -in $site_5_0 -x 30 -y 110 -width 339 -relwidth 0 -height 318 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_5_0.but69 \
        -in $site_5_0 -x 390 -y 110 -width 339 -relwidth 0 -height 318 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_5_0.ent75 \
        -in $site_5_0 -x 0 -relx 0.325 -y 0 -rely 0.154 -width 476 \
        -relwidth 0 -height 30 -relheight 0 -anchor nw -bordermode ignore
    place $site_5_0.lab76 \
        -in $site_5_0 -x 0 -relx 0.039 -y 0 -rely 0.154 -width 0 \
        -relwidth 0.269 -height 0 -relheight 0.064 -anchor nw \
        -bordermode ignore
    place $site_5_0.lab44 \
        -in $site_5_0 -x 0 -relx 0.039 -y 0 -rely 0.088 -height 0 \
        -relheight 0.04 -anchor nw -bordermode ignore
    place $site_5_0.ent45 \
        -in $site_5_0 -x 0 -relx 0.325 -y 0 -rely 0.066 -width 0 \
        -relwidth 0.618 -height 0 -relheight 0.066 -anchor nw \
        -bordermode ignore
    place $site_4_0.lab56 \
        -in $site_4_0 -x 10 -y 10 -width 770 -relwidth 0 -height 455 \
        -relheight 0 -anchor nw -bordermode ignore
    frame $top.tNo47.t1 \
        -background $vTcl(actual_gui_bg) -highlightcolor black
    vTcl:DefineAlias "$top.tNo47.t1" "t_notebook_t1" vTcl:WidgetProc "ddrWindow" 1
    $top.tNo47 add $top.tNo47.t1 \
        -padding 0 -sticky nsew -state normal -text View -image {} \
        -compound left -underline -1
    set site_4_1  $top.tNo47.t1
    entry $site_4_1.ent59 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black
    vTcl:DefineAlias "$site_4_1.ent59" "path_entry" vTcl:WidgetProc "ddrWindow" 1
    label $site_4_1.lab60 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans} -size 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Recorded Bag Directory:}
    vTcl:DefineAlias "$site_4_1.lab60" "record_directory_label" vTcl:WidgetProc "ddrWindow" 1
    labelframe $site_4_1.lab61 \
        -font {-family {DejaVu Sans} -size 12 -weight bold} -foreground black \
        -text Recordings: -background $vTcl(actual_gui_bg) -height 425 \
        -highlightcolor black -width 340
    vTcl:DefineAlias "$site_4_1.lab61" "recordings_label_frame" vTcl:WidgetProc "ddrWindow" 1
    set site_5_0 $site_4_1.lab61
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $site_5_0.scr64 \
        -background $vTcl(actual_gui_bg) -height 75 -highlightcolor black \
        -width 125
    vTcl:DefineAlias "$site_5_0.scr64" "directory_of_bags_scroll" vTcl:WidgetProc "ddrWindow" 1
    bind $site_5_0.scr64 <<ListboxSelect>> {
        on_enter
    }

    $site_5_0.scr64.01 configure -background white \
        -cursor xterm \
        -font font21 \
        -foreground black \
        -height 3 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -selectmode single \
        -width 10
    place $site_5_0.scr64 \
        -in $site_5_0 -x 0 -relx 0.029 -y 0 -rely 0.047 -width 0 \
        -relwidth 0.929 -height 0 -relheight 0.939 -anchor nw \
        -bordermode ignore
    labelframe $site_4_1.lab62 \
        -font {-family {DejaVu Sans} -size 12 -weight bold} -foreground black \
        -text Previews: -background $vTcl(actual_gui_bg) -height 425 \
        -highlightcolor black -width 420
    vTcl:DefineAlias "$site_4_1.lab62" "previews_label_frame" vTcl:WidgetProc "ddrWindow" 1
    set site_5_0 $site_4_1.lab62
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $site_5_0.scr65 \
        -background $vTcl(actual_gui_bg) -height 75 -highlightcolor black \
        -width 125
    vTcl:DefineAlias "$site_5_0.scr65" "markdown_viewer" vTcl:WidgetProc "ddrWindow" 1

    $site_5_0.scr65.01 configure -background white \
        -cursor xterm \
        -font font21 \
        -foreground black \
        -height 3 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10
    place $site_5_0.scr65 \
        -in $site_5_0 -x 10 -y 20 -width 396 -relwidth 0 -height 399 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_4_1.ent59 \
        -in $site_4_1 -x 240 -y 10 -width 536 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_4_1.lab60 \
        -in $site_4_1 -x 20 -y 10 -width 201 -relwidth 0 -height 28 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_4_1.lab61 \
        -in $site_4_1 -x 10 -y 50 -width 340 -relwidth 0 -height 425 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_4_1.lab62 \
        -in $site_4_1 -x 360 -y 50 -width 420 -relwidth 0 -height 425 \
        -relheight 0 -anchor nw -bordermode ignore
    frame $top.tNo47.t3 \
        -background $vTcl(actual_gui_bg) -highlightcolor black
    vTcl:DefineAlias "$top.tNo47.t3" "t_notebook_t2" vTcl:WidgetProc "ddrWindow" 1
    $top.tNo47 add $top.tNo47.t3 \
        -padding 0 -sticky nsew -state normal -text Delete -image {} \
        -compound none -underline -1
    set site_4_2  $top.tNo47.t3
    labelframe $site_4_2.lab43 \
        -font {-family {DejaVu Sans} -size 12 -weight bold} -foreground black \
        -text Recordings -background $vTcl(actual_gui_bg) -height 455 \
        -highlightcolor black -width 460
    vTcl:DefineAlias "$site_4_2.lab43" "delete_frame" vTcl:WidgetProc "ddrWindow" 1
    set site_5_0 $site_4_2.lab43
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $site_5_0.scr44 \
        -background $vTcl(actual_gui_bg) -height 75 -highlightcolor black \
        -width 125
    vTcl:DefineAlias "$site_5_0.scr44" "dir_of_bags_scroll_copy" vTcl:WidgetProc "ddrWindow" 1

    $site_5_0.scr44.01 configure -background white \
        -cursor xterm \
        -font font21 \
        -foreground black \
        -height 3 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -selectmode extended \
        -width 10
    place $site_5_0.scr44 \
        -in $site_5_0 -x 0 -relx 0.022 -y 0 -rely 0.044 -width 0 \
        -relwidth 0.948 -height 0 -relheight 0.943 -anchor nw \
        -bordermode ignore
    button $site_4_2.but45 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -command delete_records \
        -font {-family {DejaVu Sans} -size 30} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Delete
    vTcl:DefineAlias "$site_4_2.but45" "delete_btn" vTcl:WidgetProc "ddrWindow" 1
    button $site_4_2.but46 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -command refresh_records \
        -font {-family {DejaVu Sans} -size 30} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Refresh
    vTcl:DefineAlias "$site_4_2.but46" "refresh_btn" vTcl:WidgetProc "ddrWindow" 1
    place $site_4_2.lab43 \
        -in $site_4_2 -x 10 -y 10 -width 460 -relwidth 0 -height 455 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_4_2.but45 \
        -in $site_4_2 -x 510 -y 20 -width 229 -relwidth 0 -height 198 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_4_2.but46 \
        -in $site_4_2 -x 510 -y 260 -width 229 -relwidth 0 -height 198 \
        -relheight 0 -anchor nw -bordermode ignore
    frame $top.tNo47.t2 \
        -background $vTcl(actual_gui_bg) -highlightcolor black
    vTcl:DefineAlias "$top.tNo47.t2" "t_notebook_t3" vTcl:WidgetProc "ddrWindow" 1
    $top.tNo47 add $top.tNo47.t2 \
        -padding 0 -sticky nsew -state normal -text Mileage -image {} \
        -compound none -underline -1
    set site_4_3  $top.tNo47.t2
    label $site_4_3.lab56 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans} -size 48} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {000.0 km/hr}
    vTcl:DefineAlias "$site_4_3.lab56" "speed_label" vTcl:WidgetProc "ddrWindow" 1
    label $site_4_3.lab57 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans} -size 48} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {0000000.00 km}
    vTcl:DefineAlias "$site_4_3.lab57" "dist_counter_label" vTcl:WidgetProc "ddrWindow" 1
    button $site_4_3.but61 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -command start_mileage_ctr \
        -font {-family {DejaVu Sans} -size 14} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -state disabled -text Start -width 158
    vTcl:DefineAlias "$site_4_3.but61" "btn_start_ctr" vTcl:WidgetProc "ddrWindow" 1
    button $site_4_3.but62 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -command stop_mileage_ctr \
        -font {-family {DejaVu Sans} -size 14} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Stop \
        -width 156
    vTcl:DefineAlias "$site_4_3.but62" "btn_stop_ctr" vTcl:WidgetProc "ddrWindow" 1
    button $site_4_3.but63 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -command reset_mileage_ctr \
        -font {-family {DejaVu Sans} -size 14} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Reset \
        -width 161
    vTcl:DefineAlias "$site_4_3.but63" "btn_reset_ctr" vTcl:WidgetProc "ddrWindow" 1
    place $site_4_3.lab56 \
        -in $site_4_3 -x 180 -y 80 -width 430 -relwidth 0 -height 64 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_4_3.lab57 \
        -in $site_4_3 -x 140 -y 210 -width 520 -relwidth 0 -height 74 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_4_3.but61 \
        -in $site_4_3 -x 90 -y 350 -width 158 -relwidth 0 -height 58 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_4_3.but62 \
        -in $site_4_3 -x 320 -y 350 -width 156 -relwidth 0 -height 58 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_4_3.but63 \
        -in $site_4_3 -x 550 -y 350 -width 161 -relwidth 0 -height 58 \
        -relheight 0 -anchor nw -bordermode ignore
    frame $top.tNo47.t4 \
        -background $vTcl(actual_gui_bg) -highlightcolor black
    vTcl:DefineAlias "$top.tNo47.t4" "t_notebook_t4" vTcl:WidgetProc "ddrWindow" 1
    $top.tNo47 add $top.tNo47.t4 \
        -padding 0 -sticky nsew -state normal -text Topics -image {} \
        -compound none -underline -1
    set site_4_4  $top.tNo47.t4
    labelframe $site_4_4.lab43 \
        -font {-family {DejaVu Sans} -size 12 -weight bold} -foreground black \
        -text {All Topics} -background $vTcl(actual_gui_bg) -height 465 \
        -highlightcolor black -width 380
    vTcl:DefineAlias "$site_4_4.lab43" "all_topics_label_frame" vTcl:WidgetProc "ddrWindow" 1
    set site_5_0 $site_4_4.lab43
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $site_5_0.scr44 \
        -background $vTcl(actual_gui_bg) -height 75 -highlightcolor black \
        -width 125
    vTcl:DefineAlias "$site_5_0.scr44" "all_topics_scroll_lb" vTcl:WidgetProc "ddrWindow" 1

    $site_5_0.scr44.01 configure -background white \
        -cursor xterm \
        -font font21 \
        -foreground black \
        -height 3 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10
    place $site_5_0.scr44 \
        -in $site_5_0 -x 10 -y 20 -width 356 -relwidth 0 -height 434 \
        -relheight 0 -anchor nw -bordermode ignore
    labelframe $site_4_4.lab45 \
        -font {-family {DejaVu Sans} -size 12 -weight bold} -foreground black \
        -text {Active Topics} -background $vTcl(actual_gui_bg) -height 465 \
        -highlightcolor black -width 380
    vTcl:DefineAlias "$site_4_4.lab45" "active_topics_label_frame" vTcl:WidgetProc "ddrWindow" 1
    set site_5_0 $site_4_4.lab45
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $site_5_0.scr46 \
        -background $vTcl(actual_gui_bg) -height 75 -highlightcolor black \
        -width 125
    vTcl:DefineAlias "$site_5_0.scr46" "active_topics_scroll_lb" vTcl:WidgetProc "ddrWindow" 1

    $site_5_0.scr46.01 configure -background white \
        -cursor xterm \
        -font font21 \
        -foreground black \
        -height 3 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10
    place $site_5_0.scr46 \
        -in $site_5_0 -x 10 -y 20 -width 356 -relwidth 0 -height 434 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_4_4.lab43 \
        -in $site_4_4 -x 400 -y 10 -width 380 -relwidth 0 -height 465 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_4_4.lab45 \
        -in $site_4_4 -x 10 -y 10 -width 380 -relwidth 0 -height 465 \
        -relheight 0 -anchor nw -bordermode ignore
    frame $top.tNo47.t5 \
        -background $vTcl(actual_gui_bg) -highlightcolor black
    vTcl:DefineAlias "$top.tNo47.t5" "t_notebook_t5" vTcl:WidgetProc "ddrWindow" 1
    $top.tNo47 add $top.tNo47.t5 \
        -padding 0 -sticky nsew -state normal -text Health -image {} \
        -compound none -underline -1
    set site_4_5  $top.tNo47.t5
    ttk::style configure Treeview \
         -font  "$vTcl(actual_gui_font_treeview_desc)"
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd $site_4_5.scr44 \
        -background $vTcl(actual_gui_bg) -height 15 -highlightcolor black \
        -width 30
    vTcl:DefineAlias "$site_4_5.scr44" "health_scrolled_treeview" vTcl:WidgetProc "ddrWindow" 1

    .top42.tNo47.t5.scr44.01 configure -columns "expectedHz actualHz" \
        -height 4
        .top42.tNo47.t5.scr44.01 configure -columns {expectedHz actualHz}
        .top42.tNo47.t5.scr44.01 heading #0 -text {Tree}
        .top42.tNo47.t5.scr44.01 heading #0 -anchor center
        .top42.tNo47.t5.scr44.01 column #0 -width 308
        .top42.tNo47.t5.scr44.01 column #0 -minwidth 20
        .top42.tNo47.t5.scr44.01 column #0 -stretch 1
        .top42.tNo47.t5.scr44.01 column #0 -anchor w
        .top42.tNo47.t5.scr44.01 heading expectedHz -anchor center
        .top42.tNo47.t5.scr44.01 column expectedHz -width 224
        .top42.tNo47.t5.scr44.01 column expectedHz -minwidth 20
        .top42.tNo47.t5.scr44.01 column expectedHz -stretch 1
        .top42.tNo47.t5.scr44.01 column expectedHz -anchor w
        .top42.tNo47.t5.scr44.01 heading actualHz -anchor center
        .top42.tNo47.t5.scr44.01 column actualHz -width 224
        .top42.tNo47.t5.scr44.01 column actualHz -minwidth 20
        .top42.tNo47.t5.scr44.01 column actualHz -stretch 1
        .top42.tNo47.t5.scr44.01 column actualHz -anchor w
    label $site_4_5.lab43 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans} -size 10} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Valid
    vTcl:DefineAlias "$site_4_5.lab43" "valid_lbl" vTcl:WidgetProc "ddrWindow" 1
    label $site_4_5.lab44 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans} -size 10} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Not Found}
    vTcl:DefineAlias "$site_4_5.lab44" "not_found_lbl" vTcl:WidgetProc "ddrWindow" 1
    label $site_4_5.lab45 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans} -size 10} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Invalid
    vTcl:DefineAlias "$site_4_5.lab45" "invalid_lbl" vTcl:WidgetProc "ddrWindow" 1
    canvas $site_4_5.can46 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -closeenough 1.0 \
        -height 31 -highlightcolor black -insertbackground black \
        -relief ridge -selectbackground #c4c4c4 -selectforeground black \
        -width 121
    vTcl:DefineAlias "$site_4_5.can46" "valid_canvas" vTcl:WidgetProc "ddrWindow" 1
    canvas $site_4_5.can47 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -closeenough 1.0 \
        -height 31 -highlightcolor black -insertbackground black \
        -relief ridge -selectbackground #c4c4c4 -selectforeground black \
        -width 121
    vTcl:DefineAlias "$site_4_5.can47" "not_found_canvas" vTcl:WidgetProc "ddrWindow" 1
    canvas $site_4_5.can48 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -closeenough 1.0 \
        -height 31 -highlightcolor black -insertbackground black \
        -relief ridge -selectbackground #c4c4c4 -selectforeground black \
        -width 121
    vTcl:DefineAlias "$site_4_5.can48" "invalid_canvas" vTcl:WidgetProc "ddrWindow" 1
    place $site_4_5.scr44 \
        -in $site_4_5 -x 10 -y 10 -width 770 -relwidth 0 -height 418 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_4_5.lab43 \
        -in $site_4_5 -x 60 -y 440 -width 37 -relwidth 0 -height 29 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_4_5.lab44 \
        -in $site_4_5 -x 280 -y 440 -width 70 -relwidth 0 -height 29 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_4_5.lab45 \
        -in $site_4_5 -x 510 -y 440 -width 68 -relwidth 0 -height 29 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_4_5.can46 \
        -in $site_4_5 -x 110 -y 440 -width 121 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_4_5.can47 \
        -in $site_4_5 -x 360 -y 440 -width 121 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_4_5.can48 \
        -in $site_4_5 -x 590 -y 440 -width 121 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore
    frame $top.tNo47.t6 \
        -background $vTcl(actual_gui_bg) -highlightcolor black
    vTcl:DefineAlias "$top.tNo47.t6" "t_notebook_t6" vTcl:WidgetProc "ddrWindow" 1
    $top.tNo47 add $top.tNo47.t6 \
        -padding 0 -sticky nsew -state normal -text {KML Publisher} -image {} \
        -compound none -underline -1
    set site_4_6  $top.tNo47.t6
    labelframe $site_4_6.lab44 \
        -font TkDefaultFont -foreground black -text {All Modes} \
        -background $vTcl(actual_gui_bg) -height 365 -highlightcolor black \
        -width 349
    vTcl:DefineAlias "$site_4_6.lab44" "all_modes_label_frame" vTcl:WidgetProc "ddrWindow" 1
    set site_5_0 $site_4_6.lab44
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $site_5_0.scr47 \
        -background $vTcl(actual_gui_bg) -height 75 -highlightcolor black \
        -width 125
    vTcl:DefineAlias "$site_5_0.scr47" "all_mode_scroll_lb" vTcl:WidgetProc "ddrWindow" 1

    $site_5_0.scr47.01 configure -background white \
        -cursor xterm \
        -font font10 \
        -foreground black \
        -height 3 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -selectmode extended \
        -width 10
    place $site_5_0.scr47 \
        -in $site_5_0 -x 0 -relx 0.029 -y 0 -rely 0.055 -width 0 \
        -relwidth 0.931 -height 0 -relheight 0.915 -anchor nw \
        -bordermode ignore
    labelframe $site_4_6.lab46 \
        -font TkDefaultFont -foreground black -text {Active Modes} \
        -background $vTcl(actual_gui_bg) -height 365 -highlightcolor black \
        -width 350
    vTcl:DefineAlias "$site_4_6.lab46" "active_modes_label_frame" vTcl:WidgetProc "ddrWindow" 1
    set site_5_0 $site_4_6.lab46
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $site_5_0.scr48 \
        -background $vTcl(actual_gui_bg) -height 75 -highlightcolor black \
        -width 125
    vTcl:DefineAlias "$site_5_0.scr48" "active_modes_scroll_lb" vTcl:WidgetProc "ddrWindow" 1

    $site_5_0.scr48.01 configure -background white \
        -cursor xterm \
        -font font10 \
        -foreground black \
        -height 3 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -selectmode extended \
        -width 10
    place $site_5_0.scr48 \
        -in $site_5_0 -x 0 -relx 0.029 -y 0 -rely 0.055 -width 0 \
        -relwidth 0.934 -height 0 -relheight 0.912 -anchor nw \
        -bordermode ignore
    button $site_4_6.but50 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -command reset_btn_click \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text Reset
    vTcl:DefineAlias "$site_4_6.but50" "btn_reset_btn" vTcl:WidgetProc "ddrWindow" 1
    button $site_4_6.but44 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -command add_btn_click \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text >>
    vTcl:DefineAlias "$site_4_6.but44" "btn_add_ctr" vTcl:WidgetProc "ddrWindow" 1
    button $site_4_6.but45 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -command remove_btn_click \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text <<
    vTcl:DefineAlias "$site_4_6.but45" "btn_remove_ctr" vTcl:WidgetProc "ddrWindow" 1
    button $site_4_6.but46 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -command submit_btn_click \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text Submit
    vTcl:DefineAlias "$site_4_6.but46" "btn_submit_ctr" vTcl:WidgetProc "ddrWindow" 1
    listbox $site_4_6.lis49 \
        -background #ff1f0f -font $vTcl(actual_gui_font_fixed_desc) \
        -foreground $vTcl(actual_gui_fg) -height 34 -highlightcolor black \
        -selectbackground #c4c4c4 -selectforeground black -width 44
    $site_4_6.lis49 configure -font "-family {DejaVu Sans Mono} -size 12"
    $site_4_6.lis49 insert end text
    vTcl:DefineAlias "$site_4_6.lis49" "btn_submit_status" vTcl:WidgetProc "ddrWindow" 1
    place $site_4_6.lab44 \
        -in $site_4_6 -x 0 -relx 0.013 -y 0 -rely 0.042 -width 0 \
        -relwidth 0.442 -height 0 -relheight 0.76 -anchor nw \
        -bordermode ignore
    place $site_4_6.lab46 \
        -in $site_4_6 -x 0 -relx 0.544 -y 0 -rely 0.042 -width 0 \
        -relwidth 0.443 -height 0 -relheight 0.76 -anchor nw \
        -bordermode ignore
    place $site_4_6.but50 \
        -in $site_4_6 -x 0 -relx 0.152 -y 0 -rely 0.854 -width 129 \
        -relwidth 0 -height 48 -relheight 0 -anchor nw -bordermode ignore
    place $site_4_6.but44 \
        -in $site_4_6 -x 0 -relx 0.468 -y 0 -rely 0.229 -width 49 -relwidth 0 \
        -height 38 -relheight 0 -anchor nw -bordermode ignore
    place $site_4_6.but45 \
        -in $site_4_6 -x 0 -relx 0.468 -y 0 -rely 0.583 -width 49 -relwidth 0 \
        -height 38 -relheight 0 -anchor nw -bordermode ignore
    place $site_4_6.but46 \
        -in $site_4_6 -x 0 -relx 0.684 -y 0 -rely 0.854 -width 129 \
        -relwidth 0 -height 48 -relheight 0 -anchor nw -bordermode ignore
    place $site_4_6.lis49 \
        -in $site_4_6 -x 0 -relx 0.911 -y 0 -rely 0.813 -width 0 \
        -relwidth 0.056 -height 0 -relheight 0.071 -anchor nw \
        -bordermode ignore
    frame $top.tNo47.t7 \
        -background $vTcl(actual_gui_bg) -highlightcolor black
    vTcl:DefineAlias "$top.tNo47.t7" "t_notebook_t7" vTcl:WidgetProc "ddrWindow" 1
    $top.tNo47 add $top.tNo47.t7 \
        -padding 0 -sticky nsew -state normal -text {Hot Keys} -image {} \
        -compound none -underline -1
    set site_4_7  $top.tNo47.t7
    labelframe $site_4_7.lab48 \
        -font TkDefaultFont -foreground black -text {All Events ListBox} \
        -background $vTcl(actual_gui_bg) -height 325 -highlightcolor black \
        -width 740
    vTcl:DefineAlias "$site_4_7.lab48" "Labelframe1" vTcl:WidgetProc "ddrWindow" 1
    set site_5_0 $site_4_7.lab48
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $site_5_0.scr49 \
        -background $vTcl(actual_gui_bg) -height 75 -highlightcolor black \
        -width 125
    vTcl:DefineAlias "$site_5_0.scr49" "all_events_lb" vTcl:WidgetProc "ddrWindow" 1

    $site_5_0.scr49.01 configure -background white \
        -cursor xterm \
        -font font26 \
        -foreground black \
        -height 3 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -selectmode extended \
        -width 10
    place $site_5_0.scr49 \
        -in $site_5_0 -x 0 -relx 0.014 -y 0 -rely 0.062 -width 0 \
        -relwidth 0.981 -height 0 -relheight 0.895 -anchor nw \
        -bordermode ignore
    button $site_4_7.but50 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -command btn_lock_click \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text Lock
    vTcl:DefineAlias "$site_4_7.but50" "btn_lock" vTcl:WidgetProc "ddrWindow" 1
    label $site_4_7.lab52 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Current Time}
    vTcl:DefineAlias "$site_4_7.lab52" "current_time_lbl" vTcl:WidgetProc "ddrWindow" 1
    label $site_4_7.lab54 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Locked Time}
    vTcl:DefineAlias "$site_4_7.lab54" "locked_time_lbl" vTcl:WidgetProc "ddrWindow" 1
    button $site_4_7.but55 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -command btn_publish_click \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text Publish
    vTcl:DefineAlias "$site_4_7.but55" "btn_publish" vTcl:WidgetProc "ddrWindow" 1
    place $site_4_7.lab48 \
        -in $site_4_7 -x 0 -relx 0.025 -y 0 -rely 0.104 -width 0 \
        -relwidth 0.937 -height 0 -relheight 0.677 -anchor nw \
        -bordermode ignore
    place $site_4_7.but50 \
        -in $site_4_7 -x 0 -relx 0.089 -y 0 -rely 0.813 -width 269 \
        -relwidth 0 -height 68 -relheight 0 -anchor nw -bordermode ignore
    place $site_4_7.lab52 \
        -in $site_4_7 -x 0 -relx 0.038 -y 0 -rely 0.021 -width 0 \
        -relwidth 0.299 -height 0 -relheight 0.079 -anchor nw \
        -bordermode ignore
    place $site_4_7.lab54 \
        -in $site_4_7 -x 0 -relx 0.595 -y 0 -rely 0.021 -width 0 \
        -relwidth 0.363 -height 0 -relheight 0.079 -anchor nw \
        -bordermode ignore
    place $site_4_7.but55 \
        -in $site_4_7 -x 0 -relx 0.544 -y 0 -rely 0.813 -width 271 \
        -relwidth 0 -height 68 -relheight 0 -anchor nw -bordermode ignore
    frame $top.tNo47.t8 \
        -background $vTcl(actual_gui_bg) -highlightcolor black
    vTcl:DefineAlias "$top.tNo47.t8" "t_notebook_t8" vTcl:WidgetProc "ddrWindow" 1
    $top.tNo47 add $top.tNo47.t8 \
        -padding 0 -sticky nsew -state normal -text Versioning -image {} \
        -compound none -underline -1
    set site_4_8  $top.tNo47.t8
    label $site_4_8.lab45 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans Mono} -size 12} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {UI_1 Version}
    vTcl:DefineAlias "$site_4_8.lab45" "lbl_ui_one_version" vTcl:WidgetProc "ddrWindow" 1
    label $site_4_8.lab46 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans Mono} -size 12} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {UI_2 Version}
    vTcl:DefineAlias "$site_4_8.lab46" "lbl_ui_two_version" vTcl:WidgetProc "ddrWindow" 1
    label $site_4_8.lab47 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans Mono} -size 12} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Vendor
    vTcl:DefineAlias "$site_4_8.lab47" "lbl_vendor" vTcl:WidgetProc "ddrWindow" 1
    label $site_4_8.lab52 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans Mono} -size 12} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Autonomy Version}
    vTcl:DefineAlias "$site_4_8.lab52" "lbl_autonomy_version" vTcl:WidgetProc "ddrWindow" 1
    entry $site_4_8.ent53 \
        -background white -font $vTcl(actual_gui_font_fixed_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 226
    vTcl:DefineAlias "$site_4_8.ent53" "entry_ui_two_version" vTcl:WidgetProc "ddrWindow" 1
    entry $site_4_8.ent54 \
        -background white -font $vTcl(actual_gui_font_fixed_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 226
    vTcl:DefineAlias "$site_4_8.ent54" "entry_ui_one_version" vTcl:WidgetProc "ddrWindow" 1
    entry $site_4_8.ent55 \
        -background white -font $vTcl(actual_gui_font_fixed_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 226
    vTcl:DefineAlias "$site_4_8.ent55" "entry_autonomy_version" vTcl:WidgetProc "ddrWindow" 1
    entry $site_4_8.ent56 \
        -background white -font $vTcl(actual_gui_font_fixed_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 226
    vTcl:DefineAlias "$site_4_8.ent56" "entry_vendor" vTcl:WidgetProc "ddrWindow" 1
    place $site_4_8.lab45 \
        -in $site_4_8 -x 0 -relx 0.203 -y 0 -rely 0.375 -width 0 \
        -relwidth 0.175 -height 0 -relheight 0.058 -anchor nw \
        -bordermode ignore
    place $site_4_8.lab46 \
        -in $site_4_8 -x 0 -relx 0.203 -y 0 -rely 0.563 -width 0 \
        -relwidth 0.168 -height 0 -relheight 0.058 -anchor nw \
        -bordermode ignore
    place $site_4_8.lab47 \
        -in $site_4_8 -x 0 -relx 0.203 -y 0 -rely 0.729 -width 0 \
        -relwidth 0.095 -height 0 -relheight 0.058 -anchor nw \
        -bordermode ignore
    place $site_4_8.lab52 \
        -in $site_4_8 -x 0 -relx 0.203 -y 0 -rely 0.188 -width 0 \
        -relwidth 0.22 -height 0 -relheight 0.058 -anchor nw \
        -bordermode ignore
    place $site_4_8.ent53 \
        -in $site_4_8 -x 0 -relx 0.468 -y 0 -rely 0.563 -width 0 \
        -relwidth 0.286 -height 0 -relheight 0.063 -anchor nw \
        -bordermode ignore
    place $site_4_8.ent54 \
        -in $site_4_8 -x 0 -relx 0.468 -y 0 -rely 0.375 -width 0 \
        -relwidth 0.286 -height 0 -relheight 0.063 -anchor nw \
        -bordermode ignore
    place $site_4_8.ent55 \
        -in $site_4_8 -x 0 -relx 0.468 -y 0 -rely 0.188 -width 0 \
        -relwidth 0.286 -height 0 -relheight 0.063 -anchor nw \
        -bordermode ignore
    place $site_4_8.ent56 \
        -in $site_4_8 -x 0 -relx 0.468 -y 0 -rely 0.729 -width 0 \
        -relwidth 0.286 -height 0 -relheight 0.063 -anchor nw \
        -bordermode ignore
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $top.scr44 \
        -background $vTcl(actual_gui_bg) -height 75 -highlightcolor black \
        -width 125
    vTcl:DefineAlias "$top.scr44" "txt_alerts" vTcl:WidgetProc "ddrWindow" 1

    $top.scr44.01 configure -background white \
        -cursor xterm \
        -font font21 \
        -foreground black \
        -height 3 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $top.scr43 \
        -background $vTcl(actual_gui_bg) -height 75 -highlightcolor black \
        -width 125
    vTcl:DefineAlias "$top.scr43" "health_alerts" vTcl:WidgetProc "ddrWindow" 1

    $top.scr43.01 configure -background white \
        -cursor xterm \
        -font font21 \
        -foreground black \
        -height 3 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab47 \
        -in $top -x 0 -y 510 -width 66 -relwidth 0 -height 28 -relheight 0 \
        -anchor nw -bordermode ignore
    place $top.lab70 \
        -in $top -x 0 -y 720 -width 66 -relwidth 0 -height 28 -relheight 0 \
        -anchor nw -bordermode ignore
    place $top.tNo47 \
        -in $top -x 0 -y 0 -width 0 -relwidth 1 -height 0 -relheight 0.538 \
        -anchor nw -bordermode ignore
    place $top.scr44 \
        -in $top -x 0 -y 0 -rely 0.578 -width 0 -relwidth 0.992 -height 0 \
        -relheight 0.191 -anchor nw -bordermode ignore
    place $top.scr43 \
        -in $top -x 0 -y 750 -width 786 -relwidth 0 -height 184 -relheight 0 \
        -anchor nw -bordermode ignore
    } ;# end vTcl:withBusyCursor

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}
